# Generated by Django 4.2.7 on 2023-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=200, null=True)),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                ("usuario", models.CharField(blank=True, max_length=200, null=True)),
                ("contraseña", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("stock", models.DecimalField(decimal_places=2, max_digits=60)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=60)),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "order_with_respect_to": "descripcion",
            },
        ),
    ]
