# Generated by Django 4.2.7 on 2023-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "producto",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("ticket", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "venta",
                "verbose_name_plural": "ventas",
                "order_with_respect_to": "fecha_pedido",
            },
        ),
    ]
