# Generated by Django 4.2.7 on 2023-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
