# Generated by Django 4.2.7 on 2023-12-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_venta_cantidad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venta",
            old_name="subtotal",
            new_name="PrecioUnitario",
        ),
        migrations.AlterOrderWithRespectTo(
            name="venta",
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name="venta",
            name="fecha_pedido",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="ticket",
        ),
    ]
