# Generated by Django 4.2.7 on 2023-12-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_alter_productos_precio_alter_productos_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="codigo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="productos",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="codigo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="producto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
